sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 54U4.8iii
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: sky-take-out-liam
    access-key-id: LTAI5t9i5bMCrWVpxWUPKWbo
    access-key-secret: 6JFxKc5CgBZgo7LZqpaRErT1fzsf8n
  wechat:
    appid: wxe544d70807862d35
    secret: e41b664f383a73e3071e03a56be49acf

spring:
  redis:
    host: localhost
    port: 6379
    password: 54U4.8iii
    database: 10

